version: '3.8'

services:
  block_fetcher:
    build: .
    environment:
      - RPC_URL
      - RPC_RATE_LIMIT
      - RPC_RETRY
      - RPC_TIMEOUT
      - POLLING_INTERVAL
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - REDIS_PASSWORD
      - REDIS_SSL
      - REDIS_CLUSTER
      - REDIS_MAX_BLOCKS
      - REDIS_TTL_SECONDS
      - LOG_DEBUG
      - LOG_TO_FILES
      - LOG_LEVEL
      - TEST_MODE=${TEST_MODE:-false}
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes --maxmemory ${REDIS_MAX_MEMORY:-512mb} --maxmemory-policy ${REDIS_MAXMEMORY_POLICY:-allkeys-lru}
    expose:
      - 6379
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli ping | grep -q PONG && ! redis-cli info persistence | grep -q 'loading:1'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: on-failure
    volumes:
      - ./redis_data:/data
    # Add optional password and memory configurations
    environment:
      - REDIS_PASSWORD
    profiles:
      - local
      - test

  rate-limiter:
    image: ${RATE_LIMITER_IMAGE:-ghcr.io/powerloom/rate-limiter:dockerify}
    environment:
      - DEFAULT_RATE_LIMIT=${DEFAULT_RATE_LIMIT:-1000}
    command: poetry run uvicorn app:app --host 0.0.0.0 --port ${RATE_LIMITER_PORT:-8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${RATE_LIMITER_PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - local
      - test
    env_file:
      - .env
